sandeep_dbt_tutorial:
  outputs:
    dev:
      catalog: dbt_tutorial_dev
      host: dbc-db9c4f4b-27ab.cloud.databricks.com
      http_path: /sql/1.0/warehouses/ce8541004af1742c
      schema: default
      threads: 1
      auth_type: oauth
      personal_access_token: 6cbb8ebbb8ed435c46c3d4a62ea6de14f767377abb327dbdb77dbd08796883f7
      type: databricks
  target: dev
